//! Golden runs: exact share codes, pinned to a file.
//!
//! `golden.rs` next door asserts a *property* — that a run replays to the same
//! digest it was recorded at. That property is self-consistent by
//! construction: change the simulation and both halves move together, and the
//! test stays green while every share code a player has saved quietly stops
//! working.
//!
//! This file asserts values instead. The share codes and digests here are what
//! they were when the fixture was blessed, so a refactor that changes the game
//! consistently is caught rather than waved through. That is the failure a
//! shared engine layer is most likely to cause and least likely to notice.
//!
//! To re-bless after a *deliberate* change — a `REPLAY_VERSION` bump, a
//! content change that moves the fingerprint — run with `RH_BLESS_GOLDEN=1`.
//! An extraction must never need it.

use std::fmt::Write as _;

use rh_content::Catalogue;
use rh_replay::{autoplay, RunSession};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/golden_values.txt"
);

/// Seeds per hunter. Enough to cover several villain combinations without
/// making the suite crawl; the wide sweep is `rh-cli -- corpus`.
const SEEDS: u64 = 12;

fn catalogue() -> Catalogue {
    rh_content::load_embedded().expect("embedded content")
}

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# rogue-hunter golden runs. Generated by golden_values.rs; do not hand-edit.\n\
         # hunter seed used_seed outcome commands digest share_code\n",
    );
    let _ = writeln!(
        out,
        "# content fingerprint: {:04x}",
        rh_content::content_fingerprint()
    );

    for hunter in catalogue().hunters.keys() {
        for seed in 0..SEEDS {
            let (mut session, used) = RunSession::new_from_viable_seed(seed, catalogue(), hunter)
                .unwrap_or_else(|error| panic!("{hunter} near seed {seed}: {error}"));
            let outcome = autoplay::autoplay(&mut session);
            let code = session.share_code();
            let digest = session.state_digest();

            // The code must rebuild the run it describes, or the value pinned
            // below is a record of nothing.
            let replayed =
                RunSession::from_share_code(&code, catalogue()).expect("share code replays");
            assert_eq!(
                replayed.state_digest(),
                digest,
                "{hunter} seed {seed}: replay diverged from the live run"
            );

            let _ = writeln!(
                out,
                "{hunter} {seed} {used} {} {} {digest:016x} {code}",
                outcome
                    .map(|outcome| format!("{outcome:?}"))
                    .unwrap_or_else(|| "unfinished".to_owned()),
                session.commands.len(),
            );
        }
    }
    out
}

#[test]
fn golden_runs_are_pinned() {
    let rendered = render();

    if std::env::var("RH_BLESS_GOLDEN").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset RH_BLESS_GOLDEN and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with RH_BLESS_GOLDEN=1 to create it")
    });

    let expected_lines: Vec<&str> = expected.lines().collect();
    let actual_lines: Vec<&str> = rendered.lines().collect();
    for (index, (want, got)) in expected_lines.iter().zip(&actual_lines).enumerate() {
        assert_eq!(
            want,
            got,
            "golden run {} of {FIXTURE} changed.\n\
             Every share code a player has saved decodes against the old \
             behaviour. If `rng_trace` is still green the generator is intact \
             and the change is in the simulation or in what gets serialised.",
            index + 1
        );
    }
    assert_eq!(
        expected_lines.len(),
        actual_lines.len(),
        "the set of golden runs changed size"
    );
}
