//! The wire shape of every command, pinned byte for byte.
//!
//! A share code is postcard bytes of a `Vec<Command>` behind a CRC. Postcard
//! encodes an enum as its *variant index*, so inserting a variant in the
//! middle of [`Command`] — or reordering [`Direction`] — silently renumbers
//! every later one. Every existing share code then decodes cleanly, passes its
//! CRC, matches its `REPLAY_VERSION` and its content fingerprint, and replays
//! the wrong commands.
//!
//! Nothing else in the suite catches that. Behavioural tests build a command,
//! encode it and decode it in the same process, so they agree with themselves
//! whatever the numbering is. Golden runs catch it only because their share
//! codes are pinned, and they report it as "the game changed" rather than
//! "the encoding moved". This file names it precisely.
//!
//! Sample values are arbitrary but fixed. What is being pinned is the shape —
//! the variant index and the field layout — not the payload.
//!
//! To re-bless after a *deliberate* format change, run with
//! `RH_BLESS_COMMAND_BYTES=1`, and bump [`rh_replay::REPLAY_VERSION`] in the
//! same commit. The version bump is the whole point of noticing.

use std::fmt::Write as _;

use rh_core::command::{Command, Target};
use rh_core::geometry::Direction;
use rh_core::state::ActorId;
use rh_core::world::{FeatureId, NpcId, OpportunityId};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/command_bytes.txt"
);

fn samples() -> Vec<(&'static str, Command)> {
    vec![
        ("Move", Command::Move(Direction::North)),
        ("Wait", Command::Wait),
        ("Melee", Command::Melee(Target::Actor(ActorId(7)))),
        (
            "Ranged",
            Command::Ranged {
                target: Target::Npc(NpcId(3)),
                silver: true,
            },
        ),
        (
            "Manoeuvre",
            Command::Manoeuvre {
                id: "aim".to_owned(),
                steps: vec![Direction::East, Direction::SouthWest],
            },
        ),
        (
            "Signature",
            Command::Signature {
                id: "set-snare".to_owned(),
                dir: Some(Direction::West),
                target: Some(Target::Actor(ActorId(1))),
            },
        ),
        ("UseDraught", Command::UseDraught),
        (
            "UseBindingCharm",
            Command::UseBindingCharm {
                target: Target::Actor(ActorId(2)),
            },
        ),
        ("Interact", Command::Interact(OpportunityId(11))),
        ("Talk", Command::Talk(NpcId(4))),
        ("BuyShot", Command::BuyShot(NpcId(5))),
        ("Travel", Command::Travel),
        (
            "Craft",
            Command::Craft {
                recipe: "silver-bullet".to_owned(),
            },
        ),
        ("Consecrate", Command::Consecrate),
        ("OpenGrave", Command::OpenGrave(FeatureId(9))),
        ("Force", Command::Force(Direction::SouthEast)),
        ("UncoverVillain", Command::UncoverVillain),
    ]
}

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# rogue-hunter command wire format. Generated by command_bytes.rs; do not hand-edit.\n\
         # A diff here renumbers existing share codes. See the module docs.\n",
    );

    // Every direction on its own too: Direction rides inside several commands
    // and its variant order is just as load-bearing as Command's.
    for direction in Direction::ALL {
        let bytes = postcard::to_allocvec(&direction).expect("direction encodes");
        let _ = writeln!(out, "Direction::{direction:?} = {}", hex(&bytes));
    }

    for (name, command) in samples() {
        let bytes = postcard::to_allocvec(&command).expect("command encodes");
        let _ = writeln!(out, "Command::{name} = {}", hex(&bytes));
    }
    out
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut acc, byte| {
        let _ = write!(acc, "{byte:02x}");
        acc
    })
}

#[test]
fn command_wire_format_is_pinned() {
    let rendered = render();

    if std::env::var("RH_BLESS_COMMAND_BYTES").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset RH_BLESS_COMMAND_BYTES and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with RH_BLESS_COMMAND_BYTES=1 to create it")
    });

    for (want, got) in expected.lines().zip(rendered.lines()) {
        assert_eq!(
            want, got,
            "the command wire format moved.\n\
             Existing share codes will decode to different commands, with a \
             valid CRC and a matching version. If this change is intended, \
             bump REPLAY_VERSION in the same commit."
        );
    }
    assert_eq!(
        expected.lines().count(),
        rendered.lines().count(),
        "the set of encoded commands changed size: a variant was added or removed"
    );
}

/// Sanity: the pinned bytes must actually decode back to what they encode.
/// Without this the fixture could pin a broken encoder just as happily.
#[test]
fn pinned_commands_round_trip() {
    for (name, command) in samples() {
        let bytes = postcard::to_allocvec(&command).expect("encodes");
        let back: Command = postcard::from_bytes(&bytes).expect("decodes");
        assert_eq!(back, command, "{name} did not survive a round trip");
    }
}
