//! A raw trace of the simulation PRNG, pinned to a file.
//!
//! `sequence_is_pinned` in `rng.rs` already holds the first four words, which
//! is enough to catch a rewritten generator. This is for a different failure:
//! when a golden replay goes red during a refactor, the question is whether
//! the *generator* moved or whether the same generator was merely consulted in
//! a different order. A four-word check cannot tell those apart. A long trace
//! can — if this file still matches and the replays do not, the draw order
//! changed and the RNG did not.
//!
//! The trace covers every bounded-draw helper, not just `next_u32`, because
//! `below` carries its own rejection loop: a change to the rejection predicate
//! moves `below` while leaving `next_u32` untouched.
//!
//! To re-bless after a *deliberate* change, run with `RH_BLESS_RNG_TRACE=1`.
//! Nothing in an extraction should ever need that; a diff here is the finding.

use std::fmt::Write as _;

use rh_core::rng::SimRng;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/rng_trace.txt");

/// Words per line in the rendered trace. Eight keeps a divergence to a short
/// line so the diff points at a draw index rather than a paragraph.
const PER_LINE: usize = 8;

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# rogue-hunter SimRng trace. Generated by rng_trace.rs; do not hand-edit.\n\
         # A diff in this file means the generator moved. See the module docs.\n",
    );

    for seed in [0u64, 1, 42, 0xDEAD_BEEF] {
        let mut rng = SimRng::new(seed);
        let _ = writeln!(out, "\n[next_u32 seed={seed} count=512]");
        emit(&mut out, (0..512).map(|_| rng.next_u32()));
    }

    // Bounds chosen to exercise the rejection loop rather than dodge it: 6 and
    // 100 are the real ones the game draws (dice and percent), 3 is small
    // enough that rejection fires often, and 0x8000_0001 is just above half of
    // u32::MAX, the worst case where nearly half of all draws are rejected.
    for bound in [3u32, 6, 100, 1000, 0x8000_0001] {
        let mut rng = SimRng::new(0);
        let _ = writeln!(out, "\n[below seed=0 bound={bound} count=2048]");
        emit(&mut out, (0..2048).map(|_| rng.below(bound)));
    }

    let mut rng = SimRng::new(0);
    let _ = writeln!(out, "\n[in_range seed=0 lo=2 hi=4 count=1024]");
    emit(&mut out, (0..1024).map(|_| rng.in_range(2, 4)));

    // `percent` is the one helper whose output is a bool, so it is rendered as
    // 0/1 rather than skipped: it consumes a draw either way, and a change to
    // how it consumes is exactly the kind of thing this file exists to catch.
    let mut rng = SimRng::new(0);
    let _ = writeln!(out, "\n[percent seed=0 chance=35 count=1024]");
    emit(&mut out, (0..1024).map(|_| u32::from(rng.percent(35))));

    out
}

fn emit(out: &mut String, values: impl Iterator<Item = u32>) {
    let mut column = 0;
    for value in values {
        let _ = write!(out, "{value:08x}");
        column += 1;
        if column == PER_LINE {
            out.push('\n');
            column = 0;
        } else {
            out.push(' ');
        }
    }
    if column != 0 {
        out.push('\n');
    }
}

#[test]
fn rng_trace_is_pinned() {
    let rendered = render();

    if std::env::var("RH_BLESS_RNG_TRACE").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset RH_BLESS_RNG_TRACE and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with RH_BLESS_RNG_TRACE=1 to create it")
    });

    // Compare line by line so the failure names the draw index, not the file.
    // Normalise line endings: the fixture is text and git may check it out
    // with CRLF on Windows, which is not a determinism finding.
    let expected_lines: Vec<&str> = expected.lines().collect();
    let actual_lines: Vec<&str> = rendered.lines().collect();

    let mut section = "<header>";
    for (index, (want, got)) in expected_lines.iter().zip(&actual_lines).enumerate() {
        if want.starts_with('[') {
            section = want;
        }
        assert_eq!(
            want,
            got,
            "the PRNG trace diverged at line {} of {FIXTURE}, in section {section}.\n\
             The generator changed. If that was deliberate it is a replay-format \
             change, not a refactor: every existing share code decodes against the \
             old sequence.",
            index + 1
        );
    }
    assert_eq!(
        expected_lines.len(),
        actual_lines.len(),
        "the PRNG trace changed length: the set of draws being traced moved"
    );
}
